% Plot single simulated elbow pointing task against empirical data
% Generates Figure S4 in the paper

blankSlate

A = load('EmpiricalComparisonData/60to120Comp.mat'); 
% Note: this solution can be generated by running
% MAIN_simpleAntagonist_track_o1dyn after setting thetaRange = [60,120]*pi/180

A(2) = load('EmpiricalComparisonData/60to120exc1e-5work1e-4.mat');
% Note: this solution can be generated by running
% MAIN_simpleAntagonist_track_o1dyn after setting
% thetaRange = [60,120]*pi/180;
% W.exc = 1e-5;
% W.pow = 1e-4;

fh = figure('color','w');
fh.Position(2) = fh.Position(2)-200;
lw = 1;
t= A(1).t_track*1000; % put time in ms
l = A(1).x_t(1,:);
t_adjust = [-80,t];

momentArm = 0.04;
restingTheta = pi/2;

theta2l = @(o) (o-restingTheta)*momentArm + A(1).Psim.lO;
l2theta = @(l) (l-A(1).Psim.lO)/(momentArm)+restingTheta; 



load('EmpiricalComparisonData/EmpiricalData.mat','Data');
% Note: these data are extracted from Forgaard et al. 2013 doi: 10.1152/jn.00888.2012

simColors = [1 0 0;0.25 0.25 1];

for i = 1:2
plot(t_adjust,[0,A(i).u_inp(2,:)],'--','color',simColors(i,:),'linewidth',lw)
hold on
lh(i) = plot(t_adjust,[0,-A(i).u_inp(1,:)],'--','color',simColors(i,:),'linewidth',lw);
end

ylim([-1.5 1.5])
plot(t_adjust([1,end]),[0 0],'-','color',0*[1 1 1])
ylabel('Excitation / Maximum')
lh(3) = plot(Data.ago_act_MVC(:,1),Data.ago_act_MVC(:,2)/max(Data.ago_act_MVC(:,2)),'-','color',[0.5 0 0],'linewidth',lw);
plot(Data.ant_act_MVC(:,1),-Data.ant_act_MVC(:,2)/min(Data.ant_act_MVC(:,2)),'-','color',[0.5 0.25 0],'linewidth',lw)
xlim([t_adjust(1),Data.ant_act_MVC(end,1)])

text(-20,0.5,['Agonist',newline,'Excitation'],'HorizontalAlignment','right','verticalalignment','bottom')
text(75,-0.5,['Antagonist',newline,'Excitation'],'HorizontalAlignment','right','verticalalignment','top')

yyaxis(gca,'right');
for i = 1:2
thetaDeg = l2theta(A(i).x_t(1,:))*180/pi-60;
plot(t,thetaDeg,'--','color',simColors(i,:))
hold on
end
plot(Data.deg(:,1),Data.deg(:,2),'-','color',[0.5 0.125 0],'linewidth',lw)

ylim([-80, 80])
set(gca,'YColor','k')
ylabel('Relative Displacement (^\circ)')
xlabel('Time (ms)')

text(250,65,'Elbow extension','HorizontalAlignment','right','verticalalignment','bottom')
ytick = get(gca,'ytick');
n = numel(ytick);
ytick(1:floor(n/2)) = [];
set(gca,'ytick',ytick,'linewidth',lw)

legend(lh,'Sim., base','Sim., base + Work and Exc. cost','Empirical','location','northoutside','NumColumns',3)

exportgraphics(gcf,'Figures/FigureS4.pdf')

